// <auto-generated />
namespace Travel_Trip_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class hotel_val_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hotel_val_add));
        
        string IMigrationMetadata.Id
        {
            get { return "202412191135121_hotel_val_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
