// <auto-generated />
namespace Travel_Trip_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class url_val_removed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(url_val_removed));
        
        string IMigrationMetadata.Id
        {
            get { return "202412191421177_url_val_removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
