// <auto-generated />
namespace Travel_Trip_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class upd1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upd1));
        
        string IMigrationMetadata.Id
        {
            get { return "202412190059069_upd1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
